plugins/eventer/config/routes.rb
#
resources :users_data, only: [:index, :show]

resources :qualifications, only: [:new, :create, :edit, :update, :destroy]

resources :offdays, only: [:index, :create, :destroy]

RedmineApp::Application.routes.draw do
  scope '/eventer' do
    resources :custom_filters
  end
end

match 'eventer_api',
      :to => 'eventer_api#index',
      :via => :get,
      :defaults => { format: 'json' }

match 'eventer_api',
      :to => 'eventer_api#create_assignments',
      :via => :post,
      :defaults => { format: 'json' }

match 'run_match_script',
      :to => 'python_runner#run_script',
      :via => :post,
      :as => :run_match_script

# Show the algorithm runner page
match "algorithm_runner",
      to: "algorithm_runner#index",
      via: :get,
      as: :algorithm_runner

# Endpoint to POST run the script
match "algorithm_runner/run",
      to: "algorithm_runner#run_script",
      via: :post,
      as: :run_script_algorithm

plugins/eventer/app/controllers/users_data_controller.rb
# plugins/eventer/app/controllers/users_data_controller.rb
class UsersDataController < ApplicationController
  before_action :set_user, only: [:show, :new_qualification, :create_qualification, :edit_qualification, :update_qualification]

  def index
    @users_data = User.all
  end

  def show
    @user_data = @user
    @qualifications = fetch_qualities(@user_data)
  end

  def new_qualification
    @qualification = UserRoleQualification.new
  end

  def create_qualification
    @qualification = UserRoleQualification.new(qualification_params)
    @qualification.user = @user

    if @qualification.save
      redirect_to users_data_path(@user), notice: I18n.t('flash.qualification_added')
    else
      render :new_qualification
    end
  end

  def edit_qualification
    @qualification = UserRoleQualification.find(params[:id])
  end

  def update_qualification
    @qualification = UserRoleQualification.find(params[:id])

    if @qualification.update(qualification_params)
      redirect_to users_data_path(@user), notice: I18n.t('flash.qualification_updated')
    else
      render :edit_qualification
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def fetch_qualities(user)
    UserRoleQualification
      .where(user_id: user.id)
      .includes(:role, :category)
      .map do |qualification|
      {
        id: qualification.id,
        role_name: qualification.role&.name || 'Unknown Role',
        category_name: qualification.category&.name || 'Unknown Category',
        role_id: qualification.role_id,
        rating: qualification.rating
      }
    end
  rescue => e
    Rails.logger.error "Error fetching qualities: #{e.message}"
    []
  end

  def qualification_params
    params.require(:user_role_qualification).permit(:role_id, :category_id, :rating)
  end
end

plugins/eventer/app/views/users_data/index.html.erb
<h1><%= l(:label_users_data_title) %></h1>

<p>
  <%= link_to l(:button_go_to_algorithm_runner), algorithm_runner_path, class: "button button-enhanced" %>
</p>

<% if @users_data.empty? %>
  <p class="no-data"><%= l(:label_no_users_data) %></p>
<% else %>
  <table class="users-data-table">
    <thead>
    <tr>
      <th>
        <%= link_to l(:label_name),
                    users_data_path(sort_by: (params[:sort_by] == "name_asc" ? "name_desc" : "name_asc")),
                    class: params[:sort_by]&.start_with?("name") ? "sorted" : "" %>
      </th>
      <th><%= l(:label_email) %></th>
      <th>
        <%= link_to l(:label_created_at),
                    users_data_path(sort_by: (params[:sort_by] == "created_at_asc" ? "created_at_desc" : "created_at_asc")),
                    class: params[:sort_by]&.start_with?("created_at") ? "sorted" : "" %>
      </th>
      <th><%= l(:label_actions) %></th>
    </tr>
    </thead>
    <tbody>
    <% @users_data.each do |user_data| %>
      <tr>
        <td><%= link_to h(user_data.name || user_data.login || l(:label_not_available)), users_datum_path(user_data) %></td>
        <td><%= h(user_data.respond_to?(:mail) && user_data.mail.present? ? user_data.mail : l(:label_not_available)) %></td>
        <td>
          <%= link_to l(:button_view), users_datum_path(user_data), class: "action-link" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<style>

    .users-data-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    .users-data-table th,
    .users-data-table td {
        padding: 10px;
        border: 1px solid #ddd;
        text-align: left;
    }
    .users-data-table th {
        background-color: #f4f4f4;
        font-weight: bold;
    }
    .users-data-table th.sorted {
        background-color: #e0e0e0;
    }
    .users-data-table tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    .users-data-table tr:hover {
        background-color: #f1f1f1;
    }

    .no-data {
        color: #888;
        font-style: italic;
    }
</style>

plugins/eventer/app/views/users_data/show.html.erb
<h1><%= @user_data.name %></h1>

<p>
  <%= l(:description_manage_qualifications) %>
</p>

<table class="list">
  <thead>
  <tr>
    <th><%= l(:label_role) %></th>
    <th><%= l(:label_category) %></th>
    <th><%= l(:label_rating) %></th>
    <th><%= l(:label_actions) %></th>
  </tr>
  </thead>
  <tbody>
  <% @qualifications.each do |qualification| %>
    <tr>
      <td><%= qualification[:role_name] %></td>
      <td><%= qualification[:category_name] %></td>
      <td><%= qualification[:rating] %></td>
      <td>
        <%= link_to l(:link_edit), edit_qualification_path(qualification), class: 'icon icon-edit' %> |
        <%= link_to l(:link_delete), qualification_path(qualification), method: :delete, data: { confirm: l(:confirm_delete_qualification) }, class: 'icon icon-del' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to l(:link_add_new_qualification), new_qualification_path(user_id: @user_data.id), class: 'button' %>