plugins/eventer/config/routes.rb
#
resources :users_data, only: [:index, :show]

resources :qualifications, only: [:new, :create, :edit, :update, :destroy]

resources :offdays, only: [:index, :create, :destroy]

RedmineApp::Application.routes.draw do
  scope '/eventer' do
    resources :custom_filters
  end
end

match 'eventer_api',
      :to => 'eventer_api#index',
      :via => :get,
      :defaults => { format: 'json' }

match 'eventer_api',
      :to => 'eventer_api#create_assignments',
      :via => :post,
      :defaults => { format: 'json' }

match 'run_match_script',
      :to => 'python_runner#run_script',
      :via => :post,
      :as => :run_match_script

# Show the algorithm runner page
match "algorithm_runner",
      to: "algorithm_runner#index",
      via: :get,
      as: :algorithm_runner

# Endpoint to POST run the script
match "algorithm_runner/run",
      to: "algorithm_runner#run_script",
      via: :post,
      as: :run_script_algorithm

plugins/eventer/app/controllers/qualifications_controller.rb
# plugins/eventer/app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  def new
    @qualification = UserRoleQualification.new
  end

  def edit
    @qualification = UserRoleQualification.find(params[:id])
  end

  def create
    ActiveRecord::Base.transaction do
      UserRole.create!(
        user_id: params[:user_id],
        role_id: params[:role_id]
      )

      UserRoleQualification.create!(
        user_id: params[:user_id],
        role_id: params[:role_id],
        category_id: params[:category_id],
        rating: params[:rating]
      )
    end

    redirect_to users_data_path(params[:user_id]), notice: I18n.t('flash.qualification_added')
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = I18n.t('flash.qualification_create_error', error: e.message)
    render :new
  end

  def destroy
    ActiveRecord::Base.transaction do
      qualification = UserRoleQualification.find(params[:id])
      user_id = qualification.user_id
      role_id = qualification.role_id

      qualification.destroy!

      if UserRoleQualification.where(user_id: user_id, role_id: role_id).none?
        UserRole.find_by(user_id: user_id, role_id: role_id)&.destroy!
      end
    end

    redirect_to users_data_path(params[:user_id]), notice: I18n.t('flash.qualification_deleted')
  rescue ActiveRecord::RecordNotFound
    flash[:error] = I18n.t('flash.qualification_not_found')
    redirect_to users_data_path(params[:user_id])
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = I18n.t('flash.qualification_delete_error', error: e.message)
    redirect_to users_data_path(params[:user_id])
  end
end

plugins/eventer/app/views/qualifications/_form.html.erb
<%= form_with(url: qualifications_path, local: true) do |form| %>
  <%= hidden_field_tag :user_id, params[:user_id] %>

  <p>
    <%= form.label :role_id, l(:label_role) %><br>
    <%= form.collection_select :role_id, Role.where.not(id: [1, 2]), :id, :name, prompt: l(:prompt_select_role) %>
  </p>

  <p>
    <%= form.label :category_id, l(:label_category) %><br>
    <%= form.collection_select :category_id, IssueCategory.all, :id, :name, prompt: l(:prompt_select_category) %>
  </p>

  <p>
    <%= form.label :rating, l(:label_rating) %><br>
    <%= form.number_field :rating, in: 0..10, step: 1 %>
  </p>

  <%= form.submit l(:button_save) %>
<% end %>

plugins/eventer/app/views/qualifications/edit.html.erb
<h2><%= l(:heading_edit_qualification) %></h2>

<%= render 'form', qualification: @qualification %>

<%= link_to l(:link_back), users_data_path(@qualification.user_id) %>

plugins/eventer/app/views/qualifications/new.html.erb
<h2><%= l(:heading_add_qualification) %></h2>

<%= render 'form', qualification: @qualification %>

<%= link_to l(:link_back), users_data_path(params[:user_id]) %>